version: '3.8'

networks:
  blazen_network:
    driver: bridge

services:
  pocketbase:
    build: ./pb
    restart: unless-stopped
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_public:/pb/pb_public
      - ./pb/pb_hooks:/pb/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blazen_network

